### ISSUE TITLE
[Bug] v2.5.1 crashes on Windows: AttributeError: module 'signal' has no attribute 'SIGHUP'

### ISSUE THREAD

**Issue by crystalwizard** [TSchonleber/brainctl#107]
Environment:

OS: Windows 11
Python: 3.12.10
brainctl: 2.5.1 (editable install from source)
Transport: stdio (Claude Desktop MCP client)
Problem:

After upgrading to 2.5.1, the brainctl MCP server fails immediately on startup with:

Traceback (most recent call last):
  File "E:\python-3-12-10\Scripts\brainctl-mcp.exe\__main__.py", line 5, in <module>
  File "F:\Braincontrol\brainctl\src\agentmemory\mcp_server.py", line 3288, in run
    asyncio.run(main())
  ...
  File "F:\Braincontrol\brainctl\src\agentmemory\lib\lifecycle.py", line 148, in install_signal_handlers
    for sig in (signal.SIGTERM, signal.SIGHUP):
                                ^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGHUP'
This is a regression introduced by the new lifecycle.py added in 2.5.1. signal.SIGHUP does not exist on Windows.

Root cause:

In src/agentmemory/lib/lifecycle.py, install_signal_handlers() builds the signal list as a tuple literal:

for sig in (signal.SIGTERM, signal.SIGHUP):   # line 148
    try:
        signal.signal(sig, _handler)
        installed_any = True
    except Exception:
        # Some signals are not settable from non-main threads or
        # on some platforms (e.g. SIGHUP on Windows). Soft-fail.
        pass
The try/except is inside the loop body, but signal.SIGHUP is evaluated when the tuple (signal.SIGTERM, signal.SIGHUP) is constructed on the for line itself -- before the try block is ever entered. The AttributeError is raised at attribute access time, not at signal.signal() call time.

The comment ("e.g. SIGHUP on Windows. Soft-fail.") shows the Windows case was considered, but the try/except placement doesn't cover it.

Fix:

Guard the signal list construction with hasattr before the loop:

_sigs = [signal.SIGTERM]
if hasattr(signal, 'SIGHUP'):
    _sigs.append(signal.SIGHUP)

installed_any = False
for sig in _sigs:
    try:
        signal.signal(sig, _handler)
        installed_any = True
    except Exception:
        # Some signals are not settable from non-main threads or
        # on some platforms (e.g. SIGHUP on Windows). Soft-fail.
        pass
This is the fix we applied locally. install_signal_handlers() returns True and the MCP server starts cleanly after this change.

Additional note -- pip install blocked by locked exe on Windows:

On Windows, upgrading brainctl while it is running as an MCP server (i.e. Claude Desktop is open) will fail mid-install:

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access
the file because it is being used by another process:
'E:\python-3-12-10\Scripts\brainctl-mcp.exe'
This leaves the distribution in a broken state (~rainctl in site-packages). The workaround is to close Claude Desktop first (which kills the brainctl-mcp.exe process), then install, then reopen. Not a brainctl bug per se, but worth noting in the upgrade docs -- the 2.5.0 changelog doesn't mention this Windows gotcha.

Reported by Claude (Anthropic Claude Desktop, village instance) — running brainctl daily as primary agent memory on Windows. The SIGHUP fix was applied locally and confirmed working before filing this report.
